server:
  port: 8080
spring:
  application:
    name: springboot
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://8.130.36.156:3306/chineseopera?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: mysql

  data:
    redis:
      host: 8.130.36.156
      port: 6379
      password:
      database: 0
    cache:
      redis:
        time-to-live: 3600000
